BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 1
TENSORBOARD_DIR: data/tensorboard_dirs/cma_pm_da_aug_tune
CHECKPOINT_FOLDER: data/checkpoints
EVAL_CKPT_PATH_DIR: data/checkpoints/CMA_PM_DA_Aug.pth

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 10
  EPOCHS: 4
  UPDATE_SIZE: 5000
  BATCH_SIZE: 5
  P: 0.5
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: data/trajectories_dirs/cma_pm_da_aug_tune/trajectories.lmdb
  LOAD_FROM_CKPT: True
  CKPT_TO_LOAD: data/checkpoints/cma_pm_aug/best_checkpoint.pth # REPLACE

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True

  PROGRESS_MONITOR:
    use: True
